defaults:
  - model: full_features_unet
  - data: classroom
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

device: cpu
model_dtype: float16
seed: 0

compute_errors: True
visualize_predictions: True
measure_throughput: False

predictions_dir: "."

num_warmup: 20
num_trials: 20
num_samples: 1024

preprocess_outside: True

optimizations:
  trace_model: True
  script_model: False
  optimize_for_inference: True

training:
  num_grad_steps: 5000
  
optimizer:
  lr: 0.01

logging:
  log_interval: 1
  eval_interval: 100
  
  save_ckpt: False
  ckpt_dir: ../checkpoints
  ckpt_interval: 100

wandb:
  mode: disabled
  entity: arao1
  project: fast-denoiser
  run_name_suffix: ""

hydra:  
  output_subdir: null  
  run:  
    dir: .