defaults:
  - model: full_features_unet
  - data: pbrt
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

device: cpu
seed: 0

num_warmup: 20
num_trials: 20
num_samples: 1024

preprocess_outside: True

optimizations:
  use_float16: True
  trace_model: True
  script_model: False
  optimize_for_inference: True

training:
  num_grad_steps: 5000
  
optimizer:
  lr: 0.01

logging:
  log_interval: 1
  eval_interval: 100
  
  save_ckpt: False
  ckpt_dir: ../checkpoints
  ckpt_interval: 100

wandb:
  mode: disabled
  entity: arao1
  project: fast-denoiser
  run_name_suffix: ""

hydra:  
  output_subdir: null  
  run:  
    dir: .