name: full_features_unet

features_to_use:
  rgb: 3
  albedo: 3
  # position: 3
  # surface_coords: 2
  # grad_camera_depth: 2
  # surface_normals: 3
  # shading_normals: 3
  rgb_sample_variance: 3
  # rgb_relative_sample_variance: 3
