name: full_features_unet

loss_name: l1_error # ["l1_error", "l2_error"]

features_to_use:
  rgb: 3

  # Albedo and position are for pbrt data.
  # albedo: 3
  # position: 1   # Position has x, y, z but we only take z / depth component.
  
  # Diffuse color and depth are for blender data.
  diffuse_color: 3
  depth: 1

  # surface_coords: 2
  # grad_camera_depth: 2
  
  # Surface normals are for pbrt, normal is for blender.
  # surface_normals: 3
  normal: 3
  

  # shading_normals: 3
  # rgb_sample_variance: 3
  # rgb_relative_sample_variance: 3
